version: '3.1'
services:
  mysql_db:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1 # 
      MYSQL_DATABASE: kma-care
      MYSQL_USER: nnlan
      MYSQL_PASSWORD: 1

  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=1
    ports:
      - "5672:5672"

volumes:
  mysql_db: null

